In [2]:
import pandas as pd
import numpy as np


df = pd.DataFrame([["a", "x"],
                    [np.nan, "y"],
                    ["a", np.nan],
                    ["b", "y"]], dtype="category")

from sklearn.impute import SimpleImputer
imp = SimpleImputer(strategy="most_frequent")
print(imp.fit_transform(df))

[['a' 'x']
 ['a' 'y']
 ['a' 'y']
 ['b' 'y']]


In [5]:
import pandas as pd
dataset = pd.read_csv("housing.csv")
dataset.head()

longitude  latitude  ...  median_house_value  ocean_proximity
0    -122.23     37.88  ...            452600.0         NEAR BAY
1    -122.22     37.86  ...            358500.0         NEAR BAY
2    -122.24     37.85  ...            352100.0         NEAR BAY
3    -122.25     37.85  ...            341300.0         NEAR BAY
4    -122.25     37.85  ...            342200.0         NEAR BAY

[5 rows x 10 columns]

In [6]:
dataset.isnull().values.any()

True

In [7]:
dataset.isnull().sum().sum()

207

In [8]:
X = dataset.iloc[:,2:8].values
y = dataset.iloc[:,-2].values

In [9]:
from sklearn.impute import SimpleImputer
import numpy as np
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
impute = imputer.fit(X[:,2:8])
X[:,2:8] = imputer.transform(X[:,2:8])
print(X)

[[4.1000e+01 8.8000e+02 1.2900e+02 3.2200e+02 1.2600e+02 8.3252e+00]
 [2.1000e+01 7.0990e+03 1.1060e+03 2.4010e+03 1.1380e+03 8.3014e+00]
 [5.2000e+01 1.4670e+03 1.9000e+02 4.9600e+02 1.7700e+02 7.2574e+00]
 ...
 [1.7000e+01 2.2540e+03 4.8500e+02 1.0070e+03 4.3300e+02 1.7000e+00]
 [1.8000e+01 1.8600e+03 4.0900e+02 7.4100e+02 3.4900e+02 1.8672e+00]
 [1.6000e+01 2.7850e+03 6.1600e+02 1.3870e+03 5.3000e+02 2.3886e+00]]


In [10]:
print(np.isnan(np.sum(X)))

False


**Label Encoding**

In [11]:
import pandas as pd
dataset = pd.read_csv("housing.csv")
dataset.head()

longitude  latitude  ...  median_house_value  ocean_proximity
0    -122.23     37.88  ...            452600.0         NEAR BAY
1    -122.22     37.86  ...            358500.0         NEAR BAY
2    -122.24     37.85  ...            352100.0         NEAR BAY
3    -122.25     37.85  ...            341300.0         NEAR BAY
4    -122.25     37.85  ...            342200.0         NEAR BAY

[5 rows x 10 columns]

In [12]:
dataset['ocean_proximity'].unique()

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

In [13]:
X = dataset.iloc[:,2:10].values
y = dataset.iloc[:,-2].values

In [14]:
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
X[:,-1] = labelencoder_X.fit_transform(X[:,-1])
print(X)

[[41.0 880.0 129.0 ... 8.3252 452600.0 3]
 [21.0 7099.0 1106.0 ... 8.3014 358500.0 3]
 [52.0 1467.0 190.0 ... 7.2574 352100.0 3]
 ...
 [17.0 2254.0 485.0 ... 1.7 92300.0 1]
 [18.0 1860.0 409.0 ... 1.8672 84700.0 1]
 [16.0 2785.0 616.0 ... 2.3886 89400.0 1]]


In [19]:
np.unique(X[:,-1])

array([0, 1, 2, 3, 4], dtype=object)

**One Hot Encoding**


In [20]:
import pandas as pd
veriseti = pd.read_csv("housing.csv")
veriseti.head()

longitude  latitude  ...  median_house_value  ocean_proximity
0    -122.23     37.88  ...            452600.0         NEAR BAY
1    -122.22     37.86  ...            358500.0         NEAR BAY
2    -122.24     37.85  ...            352100.0         NEAR BAY
3    -122.25     37.85  ...            341300.0         NEAR BAY
4    -122.25     37.85  ...            342200.0         NEAR BAY

[5 rows x 10 columns]

In [26]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

X = dataset.iloc[:,2:10].values
y = dataset.iloc[:,-2].values

labelencoder_X = LabelEncoder()
X[:,-1] = labelencoder_X.fit_transform(X[:,-1])
print(X)

[[41.0 880.0 129.0 ... 8.3252 452600.0 3]
 [21.0 7099.0 1106.0 ... 8.3014 358500.0 3]
 [52.0 1467.0 190.0 ... 7.2574 352100.0 3]
 ...
 [17.0 2254.0 485.0 ... 1.7 92300.0 1]
 [18.0 1860.0 409.0 ... 1.8672 84700.0 1]
 [16.0 2785.0 616.0 ... 2.3886 89400.0 1]]


In [27]:
ocean_distance = dataset.iloc[:,-1].values
onehotencoder_X = OneHotEncoder()
X = onehotencoder_X.fit_transform(ocean_distance.reshape(-1,1)).toarray()
print(X)

[[0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 ...
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]
