In [1]:
from sklearn.datasets import load_breast_cancer

<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject


In [2]:
kanser = load_breast_cancer()
from sklearn.model_selection import train_test_split
X_egitim, X_test, y_egitim, y_test = train_test_split(kanser.data,kanser.target,random_state=1)

In [3]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(X_egitim)

MinMaxScaler()

In [4]:
X_egitim_olcekli = scaler.transform(X_egitim)

In [5]:
X_egitim.min(axis=0)

array([6.981e+00, 9.710e+00, 4.379e+01, 1.435e+02, 5.263e-02, 1.938e-02,
       0.000e+00, 0.000e+00, 1.060e-01, 5.024e-02, 1.153e-01, 3.602e-01,
       7.570e-01, 6.802e+00, 1.713e-03, 2.252e-03, 0.000e+00, 0.000e+00,
       9.539e-03, 8.948e-04, 7.930e+00, 1.202e+01, 5.041e+01, 1.852e+02,
       7.117e-02, 2.729e-02, 0.000e+00, 0.000e+00, 1.566e-01, 5.521e-02])

In [6]:
X_egitim_olcekli.min(axis=0)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
X_egitim.max(axis=0)

array([2.811e+01, 3.928e+01, 1.885e+02, 2.501e+03, 1.634e-01, 2.867e-01,
       4.268e-01, 2.012e-01, 3.040e-01, 9.575e-02, 2.873e+00, 4.885e+00,
       2.198e+01, 5.422e+02, 3.113e-02, 1.354e-01, 3.960e-01, 5.279e-02,
       6.146e-02, 2.984e-02, 3.604e+01, 4.954e+01, 2.512e+02, 4.254e+03,
       2.226e-01, 9.379e-01, 1.170e+00, 2.910e-01, 5.774e-01, 1.486e-01])

In [8]:
X_egitim_olcekli.max(axis=0)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
X_test_olcekli = scaler.transform(X_test)

In [10]:
X_test_olcekli.min(axis=0)

array([ 0.0336031 ,  0.0226581 ,  0.03144219,  0.01141039,  0.14128374,
        0.04406704,  0.        ,  0.        ,  0.1540404 , -0.00615249,
       -0.00137796,  0.00594501,  0.00430665,  0.00079567,  0.03919502,
        0.0112206 ,  0.        ,  0.        , -0.03191387,  0.00664013,
        0.02660975,  0.05810235,  0.02031974,  0.00943767,  0.1094235 ,
        0.02637792,  0.        ,  0.        , -0.00023764, -0.00182032])

### Min-Max Scaling on SVM

In [12]:
from sklearn.svm import SVC
X_egitim, X_test, y_egitim, y_test = train_test_split(kanser.data,kanser.target,random_state=0)

svm = SVC(C=100,gamma='auto')
svm.fit(X_egitim,y_egitim)
svm.score(X_test,y_test)

0.6293706293706294

In [15]:
scaler = MinMaxScaler()
scaler.fit(X_egitim)
X_egitim_olcekli = scaler.transform(X_egitim)
X_test_olcekli=scaler.transform(X_test)

In [16]:
svm.fit(X_egitim_olcekli,y_egitim)
svm.score(X_test_olcekli,y_test)

0.965034965034965